"""Added extracted_keywords column to database

Revision ID: 57906a541219
Revises: 4a7478830bbb
Create Date: 2026-05-30 23:40:13.698393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57906a541219'
down_revision: Union[str, Sequence[str], None] = '4a7478830bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('extracted_keywords', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'extracted_keywords')
    # ### end Alembic commands ###
