"""Added latency column

Revision ID: c8cf3c4ed3d9
Revises: 23ec21df8fe9
Create Date: 2026-05-28 16:57:50.474148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cf3c4ed3d9'
down_revision: Union[str, Sequence[str], None] = '23ec21df8fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('latency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'latency')
    # ### end Alembic commands ###
